name: Build Files
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
          registry-url: https://registry.npmjs.com
      - run: yarn --frozen-lockfile

      - name: Cache downloads
        uses: actions/cache@v2
        with:
          path: downloads
          key: downloads-${{ hashFiles('Makefile') }}
          restore-keys: |
            downloads-

      - run: make
